format = """$directory$character"""
right_format = """$all"""

[character]
success_symbol = '[➜](bold green)'
vicmd_symbol = "[N](bold blue) "

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style) '
